name: personal_os
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  alarm: ^5.2.1
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  firebase_auth: ^6.5.4
  google_sign_in: ^7.2.0
  intl: any
  shared_preferences: ^2.5.5
  file_picker: ^11.0.2
  wakelock_plus: ^1.2.8
  audioplayers: ^6.1.0
  http: ^1.2.2
  flutter_markdown: ^0.7.4+3
  crypto: ^3.0.3
  local_auth: ^2.3.0

dependency_overrides:
  flutter_fgbg: 0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/