// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_N8pCfZqCoS-9ywj-BahsX80PPupXKHQ',
    appId: '1:104138744354:web:b19197a78b594c4940207b',
    messagingSenderId: '104138744354',
    projectId: 'personal-os-aea59',
    authDomain: 'personal-os-aea59.firebaseapp.com',
    storageBucket: 'personal-os-aea59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD5jW2BDIdSv3mHZyuRkx2p7SzsKeSGas',
    appId: '1:104138744354:android:a6cd8b63926cae3240207b',
    messagingSenderId: '104138744354',
    projectId: 'personal-os-aea59',
    storageBucket: 'personal-os-aea59.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNpVEgWDPy8m1hWjQaLHxTDKNxPG64gN0',
    appId: '1:104138744354:ios:38764792b968795a40207b',
    messagingSenderId: '104138744354',
    projectId: 'personal-os-aea59',
    storageBucket: 'personal-os-aea59.firebasestorage.app',
    iosBundleId: 'com.example.personalOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNpVEgWDPy8m1hWjQaLHxTDKNxPG64gN0',
    appId: '1:104138744354:ios:38764792b968795a40207b',
    messagingSenderId: '104138744354',
    projectId: 'personal-os-aea59',
    storageBucket: 'personal-os-aea59.firebasestorage.app',
    iosBundleId: 'com.example.personalOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_N8pCfZqCoS-9ywj-BahsX80PPupXKHQ',
    appId: '1:104138744354:web:658c105c99fb151540207b',
    messagingSenderId: '104138744354',
    projectId: 'personal-os-aea59',
    authDomain: 'personal-os-aea59.firebaseapp.com',
    storageBucket: 'personal-os-aea59.firebasestorage.app',
  );
}
